# -*- coding: utf-8 -*-
"""deploy_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nOQbsp3s_FSNDYc5KtmNeKKVc-Czr3Zt
"""



import pandas as pd
import numpy as np
import joblib
from plotly import express as px
import nltk
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from sklearn.feature_extraction.text import TfidfVectorizer

from google.colab import drive
drive.mount('/content/drive')

model_nb = joblib.load("/content/drive/MyDrive/model_naive_bayes.pkl")

data=pd.read_csv("/content/drive/MyDrive/datasettwt/Twitter_Data.csv")

data

data_test = data["clean_text"].astype(str)

data_test

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(data_test)

tfidf_matrix

predicted_sentiment = model_nb.predict(data_test)

predicted_sentiment